[[ISSUERS]]
address = "rJXxXRP5PSihKWK6xzdLcmvfdpFWZHLR9N"
name = "XPAY"

[[TOKENS]]
issuer = "rJXxXRP5PSihKWK6xzdLcmvfdpFWZHLR9N"
currency = "XPAY"
name = "X Payments"
desc = "X payments"
icon = "https://i.ibb.co/gm7v0cJ/64cebc6c19c2fe31de94c78e-X-vector-logo-download.png"

[[TOKENS.WEBLINKS]]
url = "https://x.com/XMoney"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/XMoney"
type = "socialmedia"
title = "Twitter"